config/routes.rb
Exhibo::Application.routes.draw do
  resources :industries

  resources :talents do
    resources :activities
  end

  root :to => "home#index"

  resources :users, :only => [ :show, :edit, :update ]

  match '/auth/:provider/callback' => 'sessions#create'

  match '/signin' => 'sessions#new', :as => :signin

  match '/signout' => 'sessions#destroy', :as => :signout

  match '/auth/failure' => 'sessions#failure'

end

app/models/activity.rb
class Activity
  include Mongoid::Document
  field :name
  field :created_dt, :type => DateTime, default: -> { DateTime.now }
  embedded_in :talent, :inverse_of => :activities
end

app/models/industry.rb
class Industry
  include Mongoid::Document
  field :name
  key :name
  references_many :talents
end

app/models/talent.rb
class Talent
  include Mongoid::Document
  field :fname 
  field :lname 
  field :email 
  field :summary 
  field :relocate
  field :travel
  field :job_type
  field :zip_code
  field :zip_distance
  field :updated_dt, :type => DateTime, default: -> { DateTime.now }
  embeds_many :activities
  referenced_in :industry
  PERCENT_TRAVEL = ["None", "25%", "50%", "75%", "100%"]
end

app/models/user.rb
class User
  include Mongoid::Document
  field :provider, :type => String
  field :uid, :type => String
  field :name, :type => String
  field :email, :type => String
  attr_accessible :provider, :uid, :name, :email

  def self.create_with_omniauth(auth)
    begin
      create! do |user|
        user.provider = auth['provider']
        user.uid = auth['uid']
        if auth['user_info']
          user.name = auth['user_info']['name'] if auth['user_info']['name'] # Twitter, Google, Yahoo, GitHub
          user.email = auth['user_info']['email'] if auth['user_info']['email'] # Google, Yahoo, GitHub
        end
        if auth['extra']['user_hash']
          user.name = auth['extra']['user_hash']['name'] if auth['extra']['user_hash']['name'] # Facebook
          user.email = auth['extra']['user_hash']['email'] if auth['extra']['user_hash']['email'] # Facebook
        end
      end
    rescue Exception
      raise Exception, "cannot create user record"
    end
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def create
    @talent = Talent.find(params[:talent_id])
    @activity = @talent.activities.create!(params[:activity])
    redirect_to @talent, :notice => "Activity Created"
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Mongoid::Errors::DocumentNotFound
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
  # GET /industries
  # GET /industries.json
  def index
    @industries = Industry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @industries }
    end
  end

  # GET /industries/1
  # GET /industries/1.json
  def show
    @industry = Industry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @industry }
    end
  end

  # GET /industries/new
  # GET /industries/new.json
  def new
    @industry = Industry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @industry }
    end
  end

  # GET /industries/1/edit
  def edit
    @industry = Industry.find(params[:id])
  end

  # POST /industries
  # POST /industries.json
  def create
    @industry = Industry.new(params[:industry])

    respond_to do |format|
      if @industry.save
        format.html { redirect_to @industry, notice: 'Industry was successfully created.' }
        format.json { render json: @industry, status: :created, location: @industry }
      else
        format.html { render action: "new" }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /industries/1
  # PUT /industries/1.json
  def update
    @industry = Industry.find(params[:id])

    respond_to do |format|
      if @industry.update_attributes(params[:industry])
        format.html { redirect_to @industry, notice: 'Industry was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /industries/1
  # DELETE /industries/1.json
  def destroy
    @industry = Industry.find(params[:id])
    @industry.destroy

    respond_to do |format|
      format.html { redirect_to industries_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/linked_in'
  end


  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'], 
                      :uid => auth['uid']).first || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    if !user.email
      redirect_to edit_user_path(user), :alert => "Please enter your email address."
    else
      redirect_to root_url, :notice => 'Signed in!'
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/talents_controller.rb
class TalentsController < ApplicationController
  # GET /talents
  # GET /talents.json
  def index
    @talents = Talent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @talents }
    end
  end

  # GET /talents/1
  # GET /talents/1.json
  def show
    @talent = Talent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @talent }
    end
  end

  # GET /talents/new
  # GET /talents/new.json
  def new
    @talent = Talent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @talent }
    end
  end

  # GET /talents/1/edit
  def edit
    @talent = Talent.find(params[:id])
  end

  # POST /talents
  # POST /talents.json
  def create
    @talent = Talent.new(params[:talent])

    respond_to do |format|
      if @talent.save
        format.html { redirect_to @talent, notice: 'Talent was successfully created.' }
        format.json { render json: @talent, status: :created, location: @talent }
      else
        format.html { render action: "new" }
        format.json { render json: @talent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /talents/1
  # PUT /talents/1.json
  def update
    @talent = Talent.find(params[:id])

    respond_to do |format|
      if @talent.update_attributes(params[:talent])
        format.html { redirect_to @talent, notice: 'Talent was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @talent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /talents/1
  # DELETE /talents/1.json
  def destroy
    @talent = Talent.find(params[:id])
    @talent.destroy

    respond_to do |format|
      format.html { redirect_to talents_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      render :edit
    end
  end


def show
    @user = User.find(params[:id])

  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/industries_helper.rb
module IndustriesHelper
end

app/helpers/talents_helper.rb
module TalentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
%h3 Home
- @users.each do |user|
  %p User: #{link_to user.name, user}

app/views/industries/_form.html.haml
= form_for @industry do |f|
  -if @industry.errors.any?
    #error_explanation
      %h2= "#{pluralize(@industry.errors.count, "error")} prohibited this industry from being saved:"
      %ul
        - @industry.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/industries/edit.html.haml
%h1 Editing industry

= render 'form'

= link_to 'Show', @industry
\|
= link_to 'Back', industries_path

app/views/industries/index.html.haml
%h1 Listing industries

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @industries.each do |industry|
    %tr
      %td= industry.name
      %td= link_to 'Show', industry
      %td= link_to 'Edit', edit_industry_path(industry)
      %td= link_to 'Destroy', industry, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Industry', new_industry_path

app/views/industries/new.html.haml
%h1 New industry

= render 'form'

= link_to 'Back', industries_path

app/views/industries/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @industry.name

= link_to 'Edit', edit_industry_path(@industry)
\|
= link_to 'Back', industries_path

app/views/layouts/application.html.haml
%html
  %head
    %title exhibo
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tags
    = stylesheet_link_tag 'blueprint/screen', :media => 'screen'
    = stylesheet_link_tag 'blueprint/print', :media => 'print'
  %body
  %ul.hmenu
    = render 'shared/navigation'
    - flash.each do |name, msg|
      = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
    = yield

app/views/shared/_navigation.html.haml
- if user_signed_in?
  %li
    Logged in as #{current_user.name}
  %li
    = link_to('Logout', signout_path)
- else
  %li
    = link_to('Login', signin_path)

app/views/talents/_form.html.haml
= form_for @talent do |f|
  -if @talent.errors.any?
    #error_explanation
      %h2= "#{pluralize(@talent.errors.count, "error")} prohibited this talent from being saved:"
      %ul
        - @talent.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :fname
    = f.text_field :fname
  .field
    = f.label :lname
    = f.text_field :lname
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :industry
    = f.collection_select :industry_id, Industry.all, :id, :name
  .field
    = f.label :summary
    = f.text_field :summary
  .field
    = f.label :relocate
    = f.check_box :relocate
  .field
    = f.label :travel
    = f.select :travel, Talent::PERCENT_TRAVEL
  .field
    = f.label :job_type
    = f.text_field :job_type
  .field
    = f.label :zip_code
    = f.text_field :zip_code
  .field
    = f.label :zip_distance
    = f.text_field :zip_distance
  .actions
    = f.submit 'Save'

app/views/talents/edit.html.haml
%h1 Editing talent

= render 'form'

= link_to 'Show', @talent
\|
= link_to 'Back', talents_path

app/views/talents/index.html.haml
%h1 Listing talents

%table
  %tr
    %th Fname
    %th Lname
    %th Email
    %th Summary
    %th Relocate
    %th Travel
    %th Job type
    %th Zip code
    %th Zip distance
    %th
    %th
    %th

  - @talents.each do |talent|
    %tr
      %td= talent.fname
      %td= talent.lname
      %td= talent.email
      %td= talent.summary
      %td= talent.relocate
      %td= talent.travel
      %td= talent.job_type
      %td= talent.zip_code
      %td= talent.zip_distance
      %td= link_to 'Show', talent
      %td= link_to 'Edit', edit_talent_path(talent)
      %td= link_to 'Destroy', talent, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Talent', new_talent_path

app/views/talents/new.html.haml
%h1 New talent

= render 'form'

= link_to 'Back', talents_path

app/views/talents/show.html.haml
%p#notice= notice

%p
  %b Fname:
  = @talent.fname
%p
  %b Lname:
  = @talent.lname
%p
  %b Email:
  = @talent.email
%p
  %b Summary:
  = @talent.summary
%p
  %b Relocate:
  = @talent.relocate
%p
  %b Travel:
  = @talent.travel
%p
  %b Job type:
  = @talent.job_type
%p
  %b Zip code:
  = @talent.zip_code
%p
  %b Zip distance:
  = @talent.zip_distance
%p
  %b Updated Date:
  = @talent.updated_dt

= if @talent.activities.size > 0
  %h2 Activities
  = for activity in @talent.activities
    %h3= activity.name
    %p= activity.created_dt

%h2 Activity
=form_for [@talent, Activity.new] do |f|
  %p= f.label :name
  %p= f.text_field :name
  %p= f.submit




= link_to 'Edit', edit_talent_path(@talent)
\|
= link_to 'Back', talents_path

app/views/users/edit.html.haml
= form_for(@user) do |f|
  = f.label :email
  = f.text_field :email
  %br/
  = f.submit "Sign in"

app/views/users/show.html.haml
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}